homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 39.7477
  longitude: -8.805
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 35
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Lisbon

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
#logbook:

# Track the sun
#sun:

#sensor:
#  platform: yr

camera:
  -  platform: mjpeg
    mjpeg_url: http://10.20.228.45/stream
    name: ArduCAM
   
  - platform: mjpeg
    mjpeg_url: http://10.20.228.32/stream
    name: ArduCAM_2

#MQTT config
mqtt:
  broker: 127.0.0.1
  username: modulo2
  password: modulo2
sensor:
  platform: mqtt
  name: "Temperature"
  state_topic: "sensor/temperature"
  qos: 0
  unit_of_measurement: "ºC"
sensor 2:
  platform: mqtt
  name: "Humidity"
  state_topic: "sensor/humidity"
  qos: 0
  unit_of_measurement: "%"


#Relay

switch:
  platform: mqtt
  name: "Switch1"
  state_topic: "ha/switch1"
  command_topic: "ha/switch1"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic:
  false retain: true

fan:
  platform: mqtt
  command_topic: "bedroom_fan/on/set"



# Text to speech
tts:
  platform: google

group: !include groups.yaml
