homeassistant:
# Name of the location where Home Assistant is running
  name: SmartHome Anytime Anywhere
  # Location required to calculate the time the sun rises and sets
  latitude: 39.7477
  longitude: -8.805
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 35
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Lisbon

  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:


# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  cors_allowed_origins: 
    - http://10.0.2.1:3000  
    - http://192.168.1.72:3000
    - http://10.20.228.20:3000
# Uncomment this if you are using SSL or running in Docker etc
  #  base_url: :192.168.0.110:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
#logbook:

# Track the sun
#sun:

#sensor:
#  platform: yr

camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.1.163:8081
    name: PiCam
    framerate: 10   

zone:
  name: Home
  latitude: 39.735681
  longitude: -8.821502
  radius: 50
  icon: mdi:home 


notify:
  - name: notifygmail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: smarthomeplatformnotify@gmail.com
    starttls: true
    username: smarthomeplatformnotify@gmail.com
    password: !secret mail_password
    recipient:
      - smarthomeplatformnotify@gmail.com
    sender_name: 'Smart'

#MQTT config
mqtt:
  broker: 127.0.0.1
  username: modulo2
  password: modulo2
  discovery: true
  discovery_prefix: homeassistant



sensor:

 - platform: glances
   host: 127.0.0.1 
   resources:
     - 'disk_use_percent'
     - 'disk_use'
     - 'disk_free'
     - 'memory_use_percent'
     - 'memory_use'
     - 'memory_free'
     - 'swap_use_percent'
     - 'swap_use'
     - 'swap_free'
     - 'processor_load'
     - 'process_running'
     - 'process_total'
     - 'process_thread'
     - 'process_sleeping'

   
 - platform: cpuspeed
   name: "cpuspeed"

 - platform: systemmonitor
   resources:
     - type: disk_use_percent
     - type: memory_free



#Relay

switch:
 -  platform: mqtt
    name: "Lamp"
    state_topic: "switch/lamp"
    command_topic: "switch/lamp"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic:
    false retain: true
    entity_id: switch.Lamp

 - platform: mqtt
   name: "Alarm"
   state_topic: "sensor/RFID"
   command_topic: "sensor/RFID"
   payload_on: "ARMED"
   payload_off: "DISARMED"
   false retain: true
   entity_id: switch.alarm 

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /home/homeassistant/.homeassistant/tts
    time_memory: 300
    language: 'pt'

media_player:
  - platform: vlc
    name: speaker_1
    #arguments: '--alsa-audio-device=hw:1,0'


automation:
 - alias: Turn ON FAN
   condition:  
     - condition: state
       entity_id: switch.living_room_ventilation
       state: 'off' 
   trigger:
     platform: numeric_state
     entity_id: sensor.temperature
     above: 25
   action: 
     - service: notify.notifygmail
       data:
         message: "Turn on Fan!"  
     - service: tts.google_say
       data:
         message: "A ventoinha foi ligada"



 - alias: Tomar Mediacamento
   trigger:
     platform: time
     after: '22:20:00'
   action:
     - service: tts.google_say
       data:
         message: "Atenção! Hora de tomar a medicação para a tensão arterial"



 - alias:  Trigger Alarm Away Home
   trigger: 
     - platform: state
       entity_id: sensor.living_room_door_state
       to: '1'
     - platform: state
       entity_id: sensor.room_window_state
       to: '1'
     - platform: state
       entity_id: sensor.living_room_pir_level
       to: '1'
   condition: 
     - condition: state
       entity_id: switch.alarm
       state: 'on'
   action:
     - service: notify.notifygmail
       data:
         message: "Intrusion Detected"
     - service: homeassistant.turn_on
       entity_id: switch.Buzzer
     - event: alert
       event_data:
         message: "Intrusion Detected"        


 - alias: Turn OFF ALARM
   trigger:
     - platform: state
       entity_id: switch.alarm
       state: 'off'
   action:
     - service: homeassistant.turn_off
       entity_id: switch.buzzer 
 
 - alias: Turn ON Fan
   condition:
     - condition: state
       entity_id: switch.living_room_ventilation
       state: '0'
   trigger:
     platform: numeric_state
     entity_id: sensor.living_room_temperature
     above: 25
   action:
     - service: homeassistant.turn_on
       entity_id: switch.living_room_ventilation
   

 - alias: Turn OFF FAN
   condition:
     - condition: state
       entity_id: switch.living_room_ventilation
       state: '1'
   trigger:
     platform: numeric_state
     entity_id: sensor.living_room_temperature
     below: 24
   action:
     - service: homeassistant.turn_off
       entity_id: switch.living_room_ventilation


 - alias: Lum ON
   trigger: 
     platform: state
     entity_id: sensor.living_room_light_level
     state: 'DARK'
   action:
     service: homeassistant.turn_on
     entity_id: switch.Lamp


 - alias: Lum OFF
   trigger:
     platform: state
     entity_id: sensor.living_room_light_level
     state: 'Light'
   action:
     service: homeassistant.turn_off
     entity_id: switch.lamp

 - alias: Flame Alarm
   trigger:
     platform: state
     entity_id: sensor.kitchen_flame_level
     state: 'FIRE'
   action:
     - service: homeassistant.turn_on
       entity_id: switch.Buzzer
     - event: alert
       event_data:
         message: "Fire detected!" 
     - service: notify.notifygmail
       data:
         message: "Fire detected in the Smart Home"  

 - alias: Flame Alarm OFF
   trigger:
     platform: state
     entity_id: sensor.kitchen_flame_level
     state: 'Air Safe'
   action:
     service: homeassistant.turn_off
     entity_id: switch.buzzer

 - alias: Water Alarm
   trigger:
     platform: state
     entity_id: sensor.kitchen_water_level
     state: 'FLOOD'
   action:
     - service: homeassistant.turn_on
       entity_id: switch.buzzer
     - event: alert
       event_data:
         message: "Water Detected"
     - service: notify.notifygmail
       data:
         message: "Water detected in the Smart Home"


 - alias: Water Alarm OFF
   trigger:
     platform: state
     entity_id: sensor.kitchen_water_level
     state: 'dry      '
   action:
     service: homeassistant.turn_off
     entity_id: switch.buzzer
    

 - alias: Gas Alarm
   trigger:
     platform: state
     entity_id: sensor.kitchen_gas_presence
     state: 'GAS DETECTED'
   action:
     - service: homeassistant.turn_on
       entity_id: switch.buzzer
     - event: alert
       event_data:
         message: "Gas Detected"
     - service: notifty.notifygmail
       data: 
         message: "Gas Detected in the Smart Home"
    


 - alias: Gas Alarm OFF
   trigger: 
     platform: state
     entity_id: sensor.kitchen_gas_presence
     state: 'Air Safe'
   action:
     service: homeassistant.turn_off
     entity_id: switch.buzzer

 - alias: PanicButton
   trigger:
     platform: state
     entity_id: binary_sensor.panic_button
     from: 'off'
     to: 'on'
   action:
     - service: tts.google_say
       data:
         message: "SOCORRO SOCORRO AJUDA-ME"

 - alias: Turn ON BATATAS
   condition:
     - condition: state
       entity_id: switch.eletrovalve_switch
       state: 'off'
   trigger:
     platform: numeric_state
     entity_id: sensor.soil_humidity
     below: 30
   action:
     - service: homeassistant.turn_on
       entity_id: switch.eletrovalve_switch

 - alias: Turn OFF BATATAS
   condition:
     - condition: state
       entity_id: switch.eletrovalve_switch
       state: 'on'
   trigger:
     platform: numeric_state
     entity_id: sensor.soil_humidity
     above: 70
   action:
     - service: homeassistant.turn_off
       entity_id: switch.eletrovalve_switch

   
 - alias: Turn ON CEBOLAS
   condition:
     - condition: state
       entity_id: switch.eletrovalve_switch
       state: 'off'
   trigger:
     platform: numeric_state
     entity_id: sensor.soil_humidity
     below: 30
   action:
     - service: homeassistant.turn_on
       entity_id: switch.eletrovalve_switch

 - alias: Turn OFF CEBOLAS
   condition:
     - condition: state
       entity_id: switch.eletrovalve_switch
       state: 'on'
   trigger:
     platform: numeric_state
     entity_id: sensor.soil_humidity
     above: 70
   action:
     - service: homeassistant.turn_off
       entity_id: switch.eletrovalve_switch

 - alias: Turn ON TOMATES
   condition:
     - condition: state
       entity_id: switch.eletrovalve_switch
       state: 'off'
   trigger:
     platform: numeric_state
     entity_id: sensor.soil_humidity
     below: 30
   action:
     - service: homeassistant.turn_on
       entity_id: switch.eletrovalve_switch

 - alias: Turn OFF TOMATES
   condition:
     - condition: state
       entity_id: switch.eletrovalve_switch
       state: 'on'
   trigger:
     platform: numeric_state
     entity_id: sensor.soil_humidity
     above: 70
   action:
     - service: homeassistant.turn_off
       entity_id: switch.eletrovalve_switch

 - alias: Turn ON MELANCIA
   condition:
     - condition: state
       entity_id: switch.eletrovalve_switch
       state: 'off'
   trigger:
     platform: numeric_state
     entity_id: sensor.soil_humidity
     below: 10
   action:
     - service: homeassistant.turn_on
       entity_id: switch.eletrovalve_switch

 - alias: Turn OFF MELANCIA
   condition:
     - condition: state
       entity_id: switch.eletrovalve_switch
       state: 'on'
   trigger:
     platform: numeric_state
     entity_id: sensor.soil_humidity
     above: 30
   action:
     - service: homeassistant.turn_off
       entity_id: switch.eletrovalve_switch

 - alias: Turn ON ORQUIDEAS
   condition:
     - condition: state
       entity_id: switch.eletrovalve_switch
       state: 'off'
   trigger:
     platform: numeric_state
     entity_id: sensor.soil_humidity
     below: 10
   action:
     - service: homeassistant.turn_on
       entity_id: switch.eletrovalve_switch

 - alias: Turn OFF ORQUIDEAS
   condition:
     - condition: state
       entity_id: switch.eletrovalve_switch
       state: 'on'
   trigger:
     platform: numeric_state
     entity_id: sensor.soil_humidity
     above: 30
   action:
     - service: homeassistant.turn_off
       entity_id: switch.eletrovalve_switch
 
 - alias: MAILBOX ALERT
   trigger:
     platform: state
     entity_id: sensor.mail
     state: '1'
   action:
     - service: notify.notifygmail
       data:
         message: "You got mail!!!"

 - alias: DOOR ALERT
   trigger:
     platform: state
     entity_id: sensor.doorbutton
     state: '1'
   action:
     - service: notify.notifygmail
       data:
         message: "Home Entrance Door!!!"

group: !include groups.yaml
